apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oss-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: oss-csi-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ossplugin.csi.alibabacloud.com
    volumeHandle: oss-csi-pv // The specified value must be the same as the name of the PV. nodePublishSecretRef:
      name: oss-secret
      namespace: default
    volumeAttributes:
      bucket: "mongodbvolume"
      url: "oss-ap-southeast-5.aliyuncs.com"
      otherOpts: "-o max_stat_cache_size=0 -o allow_other"
